name: multiicon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  material_design_icons_flutter: ^4.0.5955
  flutter_svg: ^0.22.0
  marquee: ^2.1.0
    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/image.jpg
  - assets/imageone.jpg
  - assets/imagetwo.jpg
  - assets/imagethree.jpg
  - assets/holi.jpg
  - assets/holis.jpg

  - assets/svg/logorabbit.svg
  
  - assets/image.jpg
  - assets/svg/headphones.svg
  - assets/svg/namaste.svg
  - assets/svg/phone.svg
  - assets/svg/whatsapp.svg
  - assets/svg/facebook.svg
  - assets/svg/gif.svg
  - assets/svg/sticker.svg
  - assets/svg/searchone.svg
  - assets/svg/reeltv.svg
  - assets/svg/featherwing.svg
  - assets/svg/dottwo.svg
  - assets/svg/profileone.svg
  - assets/svg/homeseven.svg
  - assets/svg/homesevenfill.svg
  - assets/svg/searchb.svg
  - assets/svg/searchc.svg
  - assets/svg/notificationone.svg
  - assets/svg/notificationtwo.svg
  - assets/svg/personfill.svg
  - assets/svg/personone.svg
  - assets/svg/persontwo.svg
  - assets/svg/album.svg
  - assets/svg/bag.svg
  - assets/svg/notifynew.svg
  - assets/people.jpg
  - assets/3Drenders.jpg
  - assets/splash.jpg
  - assets/parkstreet.jpg
  - assets/girl.jpg
  - assets/work.jpg
  - assets/nigga.jpg
  - assets/adventure.jpg
  - assets/blob.jpg
  - assets/googleicon.png
 



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
